Check ERB template syntax before allowing push into puppet repo

diff --git a/bin/git-update-hook-puppet b/bin/git-update-hook-puppet
--- a/bin/git-update-hook-puppet
+++ b/bin/git-update-hook-puppet
@@ -30,7 +30,6 @@ WHITE="\033[37m"
 #       do not contain "import" lines.
 #       See http://projects.puppetlabs.com/issues/9670
 #
-syntax_check="puppet parser validate"
 tmp=$(mktemp /tmp/git.update.XXXXXX)
 log=$(mktemp /tmp/git.update.log.XXXXXX)
 tree=$(mktemp /tmp/git.diff-tree.XXXXXX)
@@ -49,16 +48,29 @@ do
   test -z "$new_sha1" && continue
   # skip deletions
   [ "$new_sha1" = "0000000000000000000000000000000000000000" ] && continue
-  # Only test .pp files
+
+  basename=$(basename "$name")
+  git cat-file blob $new_sha1 > $tmp
+  set -o pipefail
+
   if [[ $name =~ [.]pp$ ]]
   then
-    #git cat-file blob $new_sha1 > $tmp
-    git cat-file blob $new_sha1 | grep -v '^import' > $tmp
-    set -o pipefail
-    $syntax_check $tmp 2>&1 | sed "s|$tmp|$name|"> $log
+    puppet parser validate $tmp 2>&1 | grep -v '^import' | sed "s|$tmp|$name|"> $log
     if [[ $? != 0 ]]
     then
       echo
+      echo -e "$(cat $log | sed 's|JOJOMOJO|'\\${RED}${name}\\${NOBOLD}'|')" >&2
+      echo -e "For more details run this: ${CYAN} git diff $old_sha1 $new_sha1 ${NOBOLD}" >&2 
+      echo
+      exit_status=1
+    fi
+  elif [[ $name =~ [.]erb$ ]]
+  then
+    erb -P -x -T '-' $tmp | ruby -c 2>&1 | sed "s|$tmp|$name|" > $log
+    if [[ $? != 0 ]]
+    then
+      echo
+      echo -e "${MAGENTA}${name} failed syntax check${NOBOLD}"
       echo -e "$(cat $log | sed 's|JOJOMOJO|'\\${RED}${name}\\${NOBOLD}'|')" >&2
       echo -e "For more details run this: ${CYAN} git diff $old_sha1 $new_sha1 ${NOBOLD}" >&2 
       echo
