[update-wdtk-rejections] update to run from a management server
This can no longer run on the application server directly as the working
copies of the Puppet repo have been removed.

Instead, run this on a management server and SSH to wherever WDTK is
based on the JSON to run the rake tasks.

diff --git a/bin/update-wdtk-rejections b/bin/update-wdtk-rejections
--- a/bin/update-wdtk-rejections
+++ b/bin/update-wdtk-rejections
@@ -5,8 +5,11 @@
 #  Run WDTK Rake tasks to generate requests to block at MTA layer and
 #  add updated file to Puppet.
 #
+# Should be run from a management server
+#
 
 WDTK_DIR=${1:-/data/vhost/www.whatdotheyknow.com/alaveteli}
+WDTK_SRV=$(jq --arg vhost "www.whatdotheyknow.com" -r '.vhosts[$vhost] | select(.servers) | .servers | .[] ' /data/vhosts.json | head -1)
 
 # Are we running as root?
 if [ "$UID" != "0" ]; then
@@ -14,9 +17,9 @@ if [ "$UID" != "0" ]; then
   exit 1
 fi
 
-# Is WDTK available where we think it is?
-if [ ! -d "$WDTK_DIR" ]; then
-  echo "WDTK doesn't appear to be available in ${WDTK_DIR}, aborting." >&2
+# Is this copy of WDTK accessible?
+ if ! ssh $WDTK_SRV "su -l foi -c 'test -d ${WDTK_DIR}'"; then
+  echo "WDTK doesn't appear to be accessible in ${WDTK_DIR} on ${WDTK_SRV}, aborting." >&2
   exit 2
 fi
 
@@ -33,11 +36,11 @@ RAKE_OUTPUT=$(mktemp)
 SORTED_OUTPUT=$(mktemp)
 
 # Update the list of requests to block
-su -l foi -c "cd ${WDTK_DIR} && bundle exec rake config_files:set_reject_incoming_at_mta REJECTED_THRESHOLD=3 AGE_IN_MONTHS=6 DRYRUN=0" > /dev/null
+ssh $WDTK_SRV "su -l foi -c 'cd ${WDTK_DIR} && bundle exec rake config_files:set_reject_incoming_at_mta REJECTED_THRESHOLD=3 AGE_IN_MONTHS=6 DRYRUN=0'" > /dev/null
 check_rake "set_reject_incoming_at_mta" $?
 
 # Export the list
-su -l foi -c "cd ${WDTK_DIR} && bundle exec rake config_files:generate_mta_rejection_list MTA=exim" > ${RAKE_OUTPUT}
+ssh $WDTK_SRV "su -l foi -c 'cd ${WDTK_DIR} && bundle exec rake config_files:generate_mta_rejection_list MTA=exim'" > ${RAKE_OUTPUT}
 check_rake "generate_mta_rejection_list" $?
 
 # Sort the list to ensure consistent comparisons.
