Only produce output from this script if the "git cvsimport" fails

diff --git a/export-cvs-to-git b/export-cvs-to-git
--- a/export-cvs-to-git
+++ b/export-cvs-to-git
@@ -1,5 +1,16 @@
 #!/bin/bash
 
-git cvsimport -o master -C /data/git/public/mysociety/ -d :local:/data/cvs/public/ mysociety
+LOG=`mktemp`
 
+if git cvsimport -o master -C /data/git/public/mysociety/ -d :local:/data/cvs/public/ mysociety > $LOG 2>&1
+then
+    rm $LOG
+    exit 0
+else
+    RESULT=$?
+    echo "git cvsimport failed:"
+    cat $LOG
+    rm $LOG
+    exit $RESULT
+fi
 
