Adding private repository

diff --git a/export-cvs-to-git b/export-cvs-to-git
--- a/export-cvs-to-git
+++ b/export-cvs-to-git
@@ -15,6 +15,19 @@ fi
 
 LOG=`mktemp`
 
+if git cvsimport -o master -C /data/git/private/mysociety/ -d :local:/data/cvs/private/ mysociety > $LOG 2>&1
+then
+    rm $LOG
+else
+    RESULT=$?
+    echo "git cvsimport failed:"
+    cat $LOG
+    rm $LOG
+    exit $RESULT
+fi
+
+LOG=`mktemp`
+
 if git cvsimport -o master -C /data/git/migrating/mysociety/ -d :local:/data/cvs/public/ mysociety > $LOG 2>&1
 then
     rm $LOG
