Make separate copy for use with intermediate migrating commands.

diff --git a/export-cvs-to-git b/export-cvs-to-git
--- a/export-cvs-to-git
+++ b/export-cvs-to-git
@@ -14,3 +14,15 @@ else
     exit $RESULT
 fi
 
+if git cvsimport -o master -C /data/git/migrating/mysociety/ -d :local:/data/cvs/public/ mysociety > $LOG 2>&1
+then
+    rm $LOG
+    exit 0
+else
+    RESULT=$?
+    echo "git cvsimport failed:"
+    cat $LOG
+    rm $LOG
+    exit $RESULT
+fi
+
