Some more paranoid checks on parameters + updates to comments, error messages

diff --git a/git-safe-to-checkout b/git-safe-to-checkout
--- a/git-safe-to-checkout
+++ b/git-safe-to-checkout
@@ -1,16 +1,16 @@
 #!/bin/bash
 #
-# git-safe-to-merge:
-# Tests if no local changes have been made to a git repository, including submodules recursively.
-# 
+# git-safe-to-checkout:
+# Succeeds if no local changes have been made to a git repository,
+# including submodules recursively.
+#
 # Parameters are:
 # $1 - directory of git repository checkout
-# $2 - git ref to check against - Name of ref (object name, a tag, or the remote-tracking branch name)
-# in git 
+# $2 - git ref to check against - name of ref (object name, a tag, or the
+#      remote-tracking branch name) in git
 #
 # Copyright (c) 2009 UK Citizens Online Democracy. All rights reserved.
 # Email: francis@mysociety.org; WWW: http://www.mysociety.org/
-#
 
 #set -x # debug
 
@@ -20,12 +20,37 @@ SCRIPT_COMMAND=$(basename $FULL_SCRIPT_COMMAND)
 set -e
 . $(dirname $FULL_SCRIPT_COMMAND)/../shlib/deployfns
 
-cd $1
-GIT_REF=$2
+if [ "$#" != "2" ]
+then
+    echo "Usage: $SCRIPT_COMMAND <directory> <git-ref>"
+    exit 2
+fi
 
-git fetch origin
-git diff --exit-code || die "Error: Uncommitted changes in the working copy."
-git diff --cached --exit-code || die "Error: Staged changes exist in the index."
+DIRECTORY="$1"
+GIT_REF="$2"
+
+cd "$DIRECTORY"
+
+# Check that we have a working tree (taken from require_work_tree in
+# git-sh-setup):
+test x$(git rev-parse --is-inside-work-tree) = xtrue || die "Error: The directory `pwd` must be a git repository with a working tree."
+
+# Check that the directory is the top level of the repository,
+# i.e. that there is a .git directory in $DIRECTORY.  (Similarly,
+# this test is suggested by git-sh-setup.)
+test -z $(git rev-parse --show-cdup) || die "Error: The directory `pwd` must be the top level of a repository."
+
+# Update all the remote-tracking branches from origin:
+git fetch origin || die "Error: 'git fetch origin' in `pwd` failed."
+
+# Check there are no changes in the working tree that aren't in the
+# index:
+git diff --exit-code || die "Error: Uncommitted changes in the working copy in `pwd`."
+
+# Check that there are no uncommitted changes in the index:
+git diff --cached --exit-code || die "Error: Staged changes exist in the index in `pwd`."
+
+# Check for any untracked files in the working tree:
 UNTRACKED_FILES=$(git ls-files --others --directory --no-empty-directory --exclude-standard)
 test -z "$UNTRACKED_FILES" || die "Error: There are untracked (and unignored files) in the repository:\n$UNTRACKED_FILES"
 
@@ -33,11 +58,11 @@ test -z "$UNTRACKED_FILES" || die "Error: There are untracked (and unignored fil
 # branches after "git fetch origin" i.e. that any changes to the
 # deployed repository have been pushed back to the blessed repository.
 BRANCH=$(git branch -r --contains `git rev-parse $GIT_REF`)
-if [ -z "$BRANCH" ] 
+if [ -z "$BRANCH" ]
 then
-    die "Error: Changes have been made in the deploy repository that are not in the blessed repository"
+    die "Error: Changes have been made in the deployed repository (in `pwd`) that are not in the blessed repository"
 fi
- 
+
 # Go through each submodule, from:
 SUBMODULES=$(git submodule status | awk '{ print $2; }')
 # ... to check that the remote-tracking branches are up to date:
@@ -57,7 +82,5 @@ do
     # is actually available in the submodule:
     cd $S
     git show $V > /dev/null 2> /dev/null || die "Error: Submodule '$S' commit '$V' not found in `pwd` (submodule hasn't been pushed, perhaps?)"
-    cd -
+    cd - > /dev/null
 done
-
-
