Updated to cope when no log files there

diff --git a/latest-log-symlink b/latest-log-symlink
--- a/latest-log-symlink
+++ b/latest-log-symlink
@@ -6,7 +6,7 @@
 # Copyright (c) 2004 UK Citizens Online Democracy. All rights reserved.
 # Email: francis@mysociety.org; WWW: http://www.mysociety.org/
 #
-# $Id: latest-log-symlink,v 1.1 2004-11-25 13:32:32 francis Exp $
+# $Id: latest-log-symlink,v 1.2 2004-12-14 17:31:28 francis Exp $
 #
 
 set -e
@@ -15,14 +15,17 @@ for VHOST in /data/vhost/*
 do
     for TYPE in access_log error_log
     do
-        LATEST=`ls -1 $VHOST/logs/$TYPE* | sort | tail -1`
-        SYMLINK=$VHOST/logs/$TYPE
-        if [ -e $SYMLINK -a ! -h $SYMLINK ]
+        LATEST=$( ls $VHOST/logs/$TYPE* 2>/dev/null | sort | tail -1 )
+        if [ x$LATEST != x ]
         then
-            echo >&2 "Error $SYMLINK is a file"
-            exit 1
+            SYMLINK=$VHOST/logs/$TYPE
+            if [ -e $SYMLINK -a ! -h $SYMLINK ]
+            then
+                echo >&2 "Error $SYMLINK is a file"
+                exit 1
+            fi
+            ln -fs $LATEST $VHOST/logs/$TYPE
         fi
-        ln -fs $LATEST $VHOST/logs/$TYPE
     done
 done
 
